

//constantes de Actions

const GET_POKEMON = 'GET_POKEMON';
const GET_TYPES = 'GET_TYPES';
const FILTER_BY_TYPE = 'FILTER_BY_TYPE';
const CREATED_DB = 'CREATED_DB';
const FILTER_ATTACK = 'FILTER_ATTACK';
const FILTER_ALPHABETICAL = 'FILTER_ALPHABETICAL';
const GET_POKEMON_DETAIL = 'GET_POKEMON_DETAIL';
const RESET_DETAIL = 'RESET_DETAIL';


module.exports = {
    GET_POKEMON,
    GET_TYPES,
    FILTER_BY_TYPE,
    CREATED_DB,
    FILTER_ATTACK,
    FILTER_ALPHABETICAL,
    GET_POKEMON_DETAIL,
    RESET_DETAIL
}
